from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from services.file_service import project_id_from_path, safe_project_name, walk_file_tree
from storage.db import db


PROJECT_NAME_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9 _.-]{0,80}$")


class ProjectCreator:
    def create(
        self,
        idea: str,
        name: str,
        path: str,
        preferred_stack: str | None = None,
        app_type: str | None = "fullstack",
        allow_overwrite: bool = False,
    ) -> dict[str, Any]:
        if not PROJECT_NAME_PATTERN.match(name):
            raise ValueError("Project name must start with a letter or number and use only letters, numbers, spaces, dashes, dots, or underscores.")

        base = Path(path).expanduser().resolve()
        base.mkdir(parents=True, exist_ok=True)
        project_dir = base / safe_project_name(name)
        if project_dir.exists() and any(project_dir.iterdir()) and not allow_overwrite:
            raise FileExistsError("Project folder already exists. Enable overwrite only after reviewing the path.")
        project_dir.mkdir(parents=True, exist_ok=True)

        scaffold = self.pick_scaffold(preferred_stack, app_type)
        files = self.base_files(name, idea, preferred_stack or "", scaffold)
        files.update(self.scaffold_files(scaffold, name, idea))

        created: list[str] = []
        for rel_path, content in files.items():
            target = project_dir / rel_path
            target.parent.mkdir(parents=True, exist_ok=True)
            if target.exists() and not allow_overwrite:
                continue
            target.write_text(content, encoding="utf-8")
            created.append(rel_path)

        project_id = project_id_from_path(project_dir)
        stack = self.stack_labels(scaffold)
        summary = f"Generated {scaffold} starter for: {idea[:220]}"
        project = db.upsert_project(project_id, name, str(project_dir), idea, stack, summary)

        return {
            "project": project,
            "createdFiles": created,
            "fileTree": walk_file_tree(project_dir, max_files=300),
            "message": f"Created {name} at {project_dir}",
        }

    def pick_scaffold(self, preferred_stack: str | None, app_type: str | None) -> str:
        signal = f"{preferred_stack or ''} {app_type or ''}".lower()
        if "static" in signal or "html" in signal:
            return "static"
        if "full" in signal or ("react" in signal and "fastapi" in signal):
            return "fullstack"
        if "firebase" in signal:
            return "react-firebase"
        if "fastapi" in signal or "python" in signal or "api" in signal:
            return "fastapi"
        if "react" in signal or "vite" in signal:
            return "react"
        return "fullstack"

    def stack_labels(self, scaffold: str) -> list[str]:
        labels = {
            "react": ["React", "TypeScript", "Vite"],
            "react-firebase": ["React", "TypeScript", "Vite", "Firebase"],
            "fastapi": ["Python", "FastAPI"],
            "fullstack": ["React", "TypeScript", "Vite", "Python", "FastAPI"],
            "static": ["HTML", "CSS", "JavaScript"],
        }
        return labels[scaffold]

    def base_files(self, name: str, idea: str, preferred_stack: str, scaffold: str) -> dict[str, str]:
        project_json = {
            "name": name,
            "idea": idea,
            "preferredStack": preferred_stack,
            "scaffold": scaffold,
            "assistant": "Sentinel Core",
            "safeMode": True,
        }
        return {
            "README.md": f"# {name}\n\n{idea}\n\nGenerated by LocalSentinel AI as a local-first starter project.\n",
            ".localsentinel/project.json": json.dumps(project_json, indent=2),
            ".localsentinel/memory.md": f"# Project Memory\n\n- Initial idea: {idea}\n- Scaffold: {scaffold}\n",
            "docs/roadmap.md": "# Roadmap\n\n- Validate core user workflow\n- Add tests\n- Prepare deployment checklist\n",
            "docs/architecture.md": f"# Architecture\n\nThis starter uses the `{scaffold}` scaffold. Keep secrets out of source control.\n",
        }

    def scaffold_files(self, scaffold: str, name: str, idea: str) -> dict[str, str]:
        if scaffold == "static":
            return self.static_files(name, idea)
        if scaffold == "fastapi":
            return self.fastapi_files(prefix="")
        if scaffold == "fullstack":
            files = {f"apps/web/{key}": value for key, value in self.react_files(name, include_firebase=False).items()}
            files.update({f"apps/api/{key}": value for key, value in self.fastapi_files(prefix="").items()})
            return files
        return self.react_files(name, include_firebase=scaffold == "react-firebase")

    def react_files(self, name: str, include_firebase: bool) -> dict[str, str]:
        deps = {
            "@vitejs/plugin-react": "^4.3.0",
            "typescript": "^5.5.0",
            "vite": "^5.4.0",
            "react": "^18.3.1",
            "react-dom": "^18.3.1",
        }
        if include_firebase:
            deps["firebase"] = "^10.12.0"
        package = {
            "name": safe_project_name(name).lower(),
            "version": "0.1.0",
            "private": True,
            "type": "module",
            "scripts": {"dev": "vite", "build": "tsc && vite build", "preview": "vite preview"},
            "dependencies": {k: v for k, v in deps.items() if k in ("react", "react-dom", "firebase")},
            "devDependencies": {k: v for k, v in deps.items() if k not in ("react", "react-dom", "firebase")},
        }
        files = {
            "package.json": json.dumps(package, indent=2),
            "index.html": '<div id="root"></div><script type="module" src="/src/main.tsx"></script>\n',
            "src/main.tsx": 'import React from "react";\nimport ReactDOM from "react-dom/client";\nimport App from "./App";\nimport "./index.css";\n\nReactDOM.createRoot(document.getElementById("root")!).render(<App />);\n',
            "src/App.tsx": f'export default function App() {{\n  return <main className="app"><h1>{name}</h1><p>Starter project ready.</p></main>;\n}}\n',
            "src/index.css": "body { margin: 0; font-family: Inter, system-ui, sans-serif; background: #08111f; color: #e5f3ff; }\n.app { min-height: 100vh; display: grid; place-items: center; text-align: center; }\n",
            "tsconfig.json": json.dumps({"compilerOptions": {"jsx": "react-jsx", "strict": True, "module": "ESNext", "target": "ES2020", "moduleResolution": "Bundler"}, "include": ["src"]}, indent=2),
        }
        if include_firebase:
            files[".env.example"] = "VITE_FIREBASE_API_KEY=\nVITE_FIREBASE_AUTH_DOMAIN=\nVITE_FIREBASE_PROJECT_ID=\n"
            files["src/firebase.ts"] = 'import { initializeApp } from "firebase/app";\n\nexport const firebaseConfig = {\n  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,\n  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,\n  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,\n};\n\nexport const firebaseApp = initializeApp(firebaseConfig);\n'
        return files

    def fastapi_files(self, prefix: str = "") -> dict[str, str]:
        return {
            "requirements.txt": "fastapi>=0.111.0\nuvicorn[standard]>=0.30.0\npydantic>=2.7.0\n",
            "main.py": 'from fastapi import FastAPI\nfrom app.routes import router\n\napp = FastAPI(title="Generated API")\napp.include_router(router)\n\n@app.get("/health")\ndef health():\n    return {"status": "ok"}\n',
            "app/routes.py": 'from fastapi import APIRouter\n\nrouter = APIRouter(prefix="/api")\n\n@router.get("/status")\ndef status():\n    return {"ready": True}\n',
            "app/config.py": 'from pydantic import BaseModel\n\nclass Settings(BaseModel):\n    app_name: str = "Generated API"\n\nsettings = Settings()\n',
            "app/__init__.py": "",
        }

    def static_files(self, name: str, idea: str) -> dict[str, str]:
        return {
            "index.html": f'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{name}</title><link rel="stylesheet" href="styles.css"></head><body><main><h1>{name}</h1><p>{idea}</p><button id="start">Start</button></main><script src="app.js"></script></body></html>\n',
            "styles.css": "body { margin: 0; min-height: 100vh; display: grid; place-items: center; background: #07111f; color: #e8f7ff; font-family: system-ui, sans-serif; } main { max-width: 720px; padding: 32px; }\n",
            "app.js": 'document.querySelector("#start")?.addEventListener("click", () => alert("Starter ready"));\n',
        }


project_creator = ProjectCreator()

